project:
  type: website
  output-dir: docs  # Ensure Quarto builds into /docs for GitHub Pages

website:
  title: "Citation Database Assessment"
  navbar:
    left:
      - href: index.qmd
        text: Technical Report
      - href: appendices.qmd
        text: Appendices
      - href: about.qmd
        text: Contributors
    right:
      - icon: github
        href: "https://github.com/laurenchenarides/compare_scopus_openalex_report"
        aria-label: "GitHub Repository"

format:
  html:
    toc: true  # Enables table of contents
    toc-depth: 3  # Adjust depth of TOC levels
    toc-location: left  # Options: left, right
    theme: default  # You can customize this
    number-sections: true  # Number sections if desired
    highlight-style: github  # Code highlighting style

editor: visual

author: 
  - name: "Lauren Chenarides, Ph.D."
    email: "Lauren.Chenarides@colostate.edu"
    affiliation: "Colorado State University"
  - name: "Calvin Bryan, Ph.D."
    email: "calvinrbryan@gmail.com"
    affiliation: "Colorado State University"    
  - name: "Rafael Ladislau"
    email: "rafa.ladis@gmail.com"
    affiliation: "RL Desenvolvimento de Sistemas LTDA"
  - name: "Julia Lane, Ph.D."
    email: "julia.lane@nyu.edu"
    affiliation: "New York University"
  - name: "Ming Wang"
    email: "Ming.Wang@colostate.edu"
    affiliation: "Colorado State University"

