project:
  type: website
  output-dir: docs  # Ensure Quarto builds into /docs for GitHub Pages

website:
  title: "Citation Database Assessment"
  navbar:
    left:
      - href: index.qmd
        text: Technical Report
      - href: appendices.qmd
        text: Appendices
    right:
      - icon: github
        href: "https://github.com/laurenchenarides/compare_scopus_openalex_report"
        aria-label: "GitHub Repository"

format:
  html:
    toc: true  # Enables table of contents
    toc-depth: 3  # Adjust depth of TOC levels
    toc-location: left  # Options: left, right
    theme: default  # You can customize this
    number-sections: true  # Number sections if desired
    highlight-style: github  # Code highlighting style
    author-title: false
    
editor: source

execute:
  freeze: auto  # Ensures all references are updated

