project:
  type: website

website:
  title: "Citation Database Assessment"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    toc: true  # Enables table of contents
    toc-depth: 3  # Adjust depth of TOC levels
    toc-location: left  # Options: left, right
    theme: default  # You can customize this
    number-sections: true  # Number sections if desired
    highlight-style: github  # Code highlighting style

editor: visual

author: 
  - name: "Lauren Chenarides"
  - name: "Calvin Bryan"
  - name: "Rafael Ladislau"
  - name: "Julia Lane"
  - name: "Ming Wang"

